spring:
 port: 9090

  #自定义静态资源路径
 resources:
    static-locations: classpath:/static/，classpath:/views/，classpath:/public/

 datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot_mybatis?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: shi123456
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    #    Ehcache配置
 devtools:
  restart:
   enabled: true
        # 设置重启的目录，添加目录的文件需要restart
   additional-paths: src/main/java
        # 解决项目自动重新编译后接口报404的问题
   poll-interval: 3000
   quiet-period: 1000
 cache:
   ehcache:
    config:classpath: ehcahe.xml

  #freemark配置
 freemarker:
    #设置模板文件路径
    template-loader-path: classpath:/views/
    #设置模板文件编码
    charset: UTF-8
    #设置模板文件后缀
    suffix: .ftl
    #设置响应类型
    content-type: text/html; charset=utf-8



#mybatis配置
mybatis:
  #设置mapper文件路径
  mapper-locations: classpath:mappers/*.xml
  #设置实体类路径
  type-aliases-package: com.shi.po
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true

#pageHelpers配置
pagehelper:
  #设置分页参数
  helperDialect: mysql



  #设置日志输出的格式
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    level: debug
  file:
    path: "."
    name: "logs/app.log"